apiVersion: v1
kind: Service
metadata:
  name: db # this name is because this worker example tries to connect to a service called db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
  # by default the type is ClusterIP
